### ISSUE TITLE
Explanation of isVersionValid needed

### ISSUE THREAD

**Issue by tmkn** [verdaccio/ui#191]
I'm currently trying to add types to
https://github.com/verdaccio/ui/blob/fdbdb6303bd3d29336eeb105efb0bf6a0fc01f0c/src/pages/Version/Version.tsx#L26
but I'm lost how to interpret the code.

`packageVersion` can apparently be optional, if it is, `isVersionValid` returns `true`?
https://github.com/verdaccio/ui/blob/fdbdb6303bd3d29336eeb105efb0bf6a0fc01f0c/src/pages/Version/Version.tsx#L29
Is that correct?

To add proper typing the signature needs to look like this:
```typescript
function isVersionValid(packageMeta: PackageMetaInterface | {}, packageVersion?: string): boolean {
```
`PackageMetaInterface | {}` comes from the fact that it is directly passed on from the ajax call:
https://github.com/verdaccio/ui/blob/fdbdb6303bd3d29336eeb105efb0bf6a0fc01f0c/src/pages/Version/Version.tsx#L50

I have to add some more checks to ensure that `packageMeta` is indeed of type `PackageMetaInterface`, inside `isVersionValid`.
What should I return in case it isn't? `false`?

I'm just confused by return `true` for `undefined` `packageVersion`.

Any help is appreciated :)

**Comment by tmkn** [comment]
@juanpicado @priscilawebdev any input  on this please ?

**Comment by juanpicado** [comment]
`isVersionValid` verifies whether the version exist in the package metadata. The main reason is anyone could do this

```
https://registry.verdaccio.org/-/web/detail/@verdaccio/active-directory/v/fakeVersion
```

and we verify wether `fakeVersion` is in the list of versions retrieved from the backend. 

<img width="1506" alt="Screen Shot 2019-10-19 at 7 39 02 AM" src="https://user-images.githubusercontent.com/558752/67138450-8df6c080-f243-11e9-8ef1-5d84f77127c8.png">

About the type. Package Metadata cannot be `void`, if the fetch fails will go to the catch.

```
useEffect(() => {
    (async () => {
      try {
        const packageMeta = (await callDetailPage(packageName, packageVersion)) as Partial<StateInterface>;
        const readMe = (await callReadme(packageName, packageVersion)) as Partial<StateInterface>;
        if (isVersionValid(packageMeta, packageVersion)) {
          setReadme(readMe);
          setPackageMeta(packageMeta);
          setIsLoading(false);
        } else {
          setIsLoading(false);
          setNotFound(true);
        }
      } catch (error) {
        setNotFound(true);
        setIsLoading(false);
      }
    })();
  }, [packageName, packageVersion]);
```

Thus, `isVersionValid` will always have a valid packageMetadata. So the type might looks like this.

```
function isVersionValid(packageMeta: PackageMetaInterface, packageVersion?: string): boolean 
```

`packageVersion` can be undefined, since this value comes from the URL, if you load `http://localhost:4872/-/web/detail/jquery`, then there is no `packageVersion` thus would be undefined. Here we handle 3 types of `packageVersion`

- `undefined`: not present in the URL
- `valid`: It is a valid version within the `packageMetadata`
- `invalid`: It is not present in the `packageMetadata`.

Hopefully this helps, let me know whether you need more feedback,

**Comment by DanielRuf** [comment]
> let me know whether you need more feedback

I assume the initial question is answered. If this is not the case please let us know.
