### ISSUE TITLE
Broken links when using reverse proxy with prefix (again)

### ISSUE THREAD

**Issue by r3wald** [verdaccio/ui#263]
**Broken links when using reverse proxy with prefix**
When connecting to verdaccio through a reverse proxy with a prefix, links break.
This was already addressed and fixed: https://github.com/verdaccio/verdaccio/issues/753
It was probably fixed in verdaccio 3.x but not in verdaccio/ui.

**To Reproduce**
see https://github.com/verdaccio/verdaccio/issues/753
and https://github.com/verdaccio/verdaccio/pull/755

**Expected behavior**
The index page should load including all assets. Asset links should start with url_prefix (from config file).

**Screenshots**
![html source](https://user-images.githubusercontent.com/4007585/41359596-22743b86-6f2b-11e8-9daa-a139d89ff521.png)

**Comment by DanielRuf** [comment]
Hi @r3wald,

thank you very much for reporting this bug.
Do you already know what has to be changed to fix that?

**Comment by 9ae8sdf76** [comment]
Hi @DanielRuf.  Is there any progress on this issue? I'm having the same problem, and it's a HUGE show-stopper; can't use verdaccio at all. Please advise.

**Comment by DanielRuf** [comment]
Hi @9ae8sdf76,

as you can see there was no update regarding this. Please provide as much information as possible so we can test it.

**Comment by juanpicado** [comment]
Context is here 

https://github.com/verdaccio/verdaccio/issues/1523#issuecomment-564188193

I will try to look into it (patience we are in holiday season 🙂 🎄)

**Comment by 9ae8sdf76** [comment]
Thank you @juanpicado. It should also be noted that not only are the resource links being written without the url_prefix, they are also being written in mixed-content (http instead of https), and the XHR URLs are written insecure as well, causing the browser to block them due to the default CSP.

**Comment by konsultaner** [comment]
@DanielRuf in `verdaccio@4.2.1` the resources were loaded with absolut paths

    https://example.de/verdaccio/-/static/837238974.css

in `verdaccio@4.4.1` the resources are loaded with relative paths to the domain.

    /-/static/837238974.css

you either need to change it back to abolut paths or remove the first `/` in order to fix it:

    -/static/837238974.css

> as you can see there was no update regarding this. Please provide as much information as possible so we can test it.

This is an obvious html problem. This has nothing to do with server config or anything else. You can simpley run a configuration in any subdirectory on any server and will experiance this issue.

**Comment by DanielRuf** [comment]
> in `verdaccio@4.4.1` the resources are loaded with relative paths to the domain.

Which is what we normally want afaik.

I think @juanpicado is already on it.

**Comment by DanielRuf** [comment]
> This is an obvious html problem. This has nothing to do with server config or anything else. You can simpley run a configuration in any subdirectory on any server and will experiance this issue.

Well we need a reproducible testcase in general, including some config parts ;-)

**Comment by DanielRuf** [comment]
Relevant: https://github.com/verdaccio/ui/blob/master/tools/webpack.config.js#L11

**Comment by konsultaner** [comment]
>>in verdaccio@4.4.1 the resources are loaded with relative paths to the domain.

> Which is what we normally want afaik.

No you want it relative to your root. If your domain is `example.com` and your entry point / root is `example.com/verdaccio/` you do not want everything to be relative to `example.com`, but currently all assets resolve to `example.com` instead of  `example.com/verdaccio/`

>Relevant: https://github.com/verdaccio/ui/blob/master/tools/webpack.config.js#L11

I have never gone through the verdaccio code, but for me it seems like this:

    publicPath: '/-/static/',

Should be changed to this:

    publicPath: '-/static/',

Thats it.

**Comment by DanielRuf** [comment]
I'm not sure about proxy setups. There were some notes about this in the past. @juanpicado might know more.

Not sure if we explicitely support verdaccio installs in subfolders.

This could be probably the solution @konsultaner but we should test this because it is used like this in many setups already. Do you want to provide a PR for this?

**Comment by DanielRuf** [comment]
See also https://verdaccio.org/docs/en/reverse-proxy

**Comment by DanielRuf** [comment]
See also https://verdaccio.org/docs/en/reverse-proxy#sub-directory

**Comment by DanielRuf** [comment]
> Context is here
> 
> [verdaccio/verdaccio#1523 (comment)](https://github.com/verdaccio/verdaccio/issues/1523#issuecomment-564188193)
> 
> I will try to look into it (patience we are in holiday season 🙂 🎄)

But afaik @juanpicado should be already on it.

**Comment by konsultaner** [comment]
> Not sure if we explicitely support verdaccio installs in subfolders.

[We recommend use a subdirectory /verdaccio/ instead a URI.](https://verdaccio.org/docs/en/configuration.html#url-prefix)

It is actually recommended

>See also https://verdaccio.org/docs/en/reverse-proxy#sub-directory

This should have no influence on reverse-proxies, because the browser resolves the subdirectory. Everything else is to be configured within the proxy. Solving this issue may break some current reverse-proxy configurations that already workaround this issue.

> Do you want to provide a PR for this?

Since I am super new to the code I'll better leave this to @juanpicado. ;-)

**Comment by 9ae8sdf76** [comment]
@konsultaner The path should most definitely not be `-/static/`, because it will assume that the current directory in the URL is the base for the path; e.g., `https://foo.bar.example/npm/assets/something/bar/-/static/` instead of `https://foo.bar.exmaple/npm/-/static/`.

Because my use-case is using mixed http/https using a reverse proxy, I believe the correct and most robust solution (i.e., the solution that would work for everybody) would be to generate [protocol-relative URLs](https://www.paulirish.com/2010/the-protocol-relative-url/):

not using `config.url_prefix`:
```
//foo.bar.example/-/static/
```

using `config.url_prefix`:
```
//foo.bar.example/npm/-/static/
```

This causes the URL to inherit the protocol (scheme) from the browser.

**Comment by 9ae8sdf76** [comment]
@DanielRuf here is my configs:

It should be noted that my company mandates that all servers live behind a load balancer (both for performance and security purposes), so I have no choice in using mixed protocols (http at my server and https at the load balancer).

The server I am using also uses satis as a composer proxy, hence the need for using a "sub-directory" (i.e., `config.url_prefix`) approach to verdaccio.

Apache:
```
<VirtualHost *:80>
    ServerName repo.example.com

    RequestHeader set Host "repo.example.com"

    DocumentRoot /var/www/html/web
    Alias "/github" "/var/www/html/callback.php"

    #LogLevel alert rewrite:trace3

    <Location /npm/>
        ProxyPreserveHost on
        ProxyPass http://127.0.0.1:4873/ nocanon
        ProxyPassReverse http://127.0.0.1:4873/

        Header always set Access-Control-Allow-Origin "http://repo.example.com"
        Header always set Vary "Origin"
        Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PUT"
        Header always set Access-Control-Max-Age "1000"
        Header always set Access-Control-Allow-Headers "*"
        Header always set Content-Security-Policy "upgrade-insecure-requests"
    </Location>

    AllowEncodedSlashes NoDecode

    <Directory /var/www/html/web>
        Options +FollowSymLinks +SymLinksIfOwnerMatch
        AllowOverride All

        RewriteEngine On

        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^-/(.+)$ /npm/-/$1 [QSA,R,L]
    </Directory>
</VirtualHost>
```

I also opted to install the `verdaccio.service` file and changed where the config file points to:

```
[Unit]
Description=Verdaccio lightweight npm proxy registry

[Service]
Type=simple
Restart=on-failure
User=verdaccio
ExecStart=/usr/local/bin/verdaccio --config /etc/verdaccio/config.yaml

[Install]
WantedBy=multi-user.target
```

My config file:

```
storage: /var/lib/verdaccio/storage
plugins: /var/lib/verdaccio/plugins

web:
  gravatar: true
  logo: /var/lib/verdaccio/logo.png
  title: UPM - Package Management

url_prefix: /npm/
https_proxy: https://repo.example.com/npm/

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

auth:
  github-auth:
    octokit:
      baseUrl: https://git.example.com/api/v3
      log:
        debug: console.debug
        info: console.log

    mode: basic
    '**':
      access: $authenticated

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish/publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated
    unpublish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true

# log settings
logs:
  - {type: file, path: /var/log/verdaccio/verdaccio.log, level: trace}
  #- {type: stdout, format: pretty, level: trace}
```

I do have the [`verdaccio-https`](https://github.com/honzahommer/verdaccio-https) plugin installed, but I added it **after** reporting this issue and hoping it'd help; it didn't make any significant difference.

The reproducible test case is simply loading the home page and looking in the network tab of the browser inspector.

**Comment by DanielRuf** [comment]
> This causes the URL to inherit the protocol (scheme) from the browser.

Not a solution / option either imo.

**Comment by DanielRuf** [comment]
> Because my use-case is using mixed http/https using a reverse proxy, I believe the correct and most robust solution (i.e., the solution that would work for everybody) would be to generate protocol-relative URLs:
> This causes the URL to inherit the protocol (scheme) from the browser.

Not a solution / option either imo.

**Comment by 9ae8sdf76** [comment]
> Not a solution / option either imo.

May I ask why?

**Comment by DanielRuf** [comment]
We may just need the base URL in the index.html file (html plugin).

Protocol less scheme is an antipattern and should not be used. It's not a problem with that and more like a workaround.

Either we use `<base>` (see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) or full absolute URLs including the protocol.

**Comment by 9ae8sdf76** [comment]
Ha! Beaten by my own reference material. :) 

For what it's worth, I wholeheartedly agree that using protocol-less schemes is not your typical solution. I only suggested it here because of the mixed protocols due to the reverse-proxy set up, and the fact that it would still work for everything else.

Let me hack a base tag in my set up real quick and I'll let you know if it makes a difference.

**Comment by 9ae8sdf76** [comment]
@DanielRuf 

One thing I forgot to mention, but was just not reminded of, is that mixing protocols causes CORS problems in the browser, even with adding a `<base>` tag. I added `<base href="ToReplaceByVerdaccio/" />` to `@verdaccio/ui-theme/static/index.html` and restarted the server (I verified it shows up in the source as expected). But it shows up as `http://...`, and causes Content-Security-Policy errors due to the mixed content:

![csp-error](https://user-images.githubusercontent.com/2528463/71836151-6f090d00-3081-11ea-9cde-d9de58a26cc4.png)

**Comment by bhumijgupta** [comment]
> See also [verdaccio.org/docs/en/reverse-proxy#sub-directory](https://verdaccio.org/docs/en/reverse-proxy#sub-directory)

I was facing a similar issue, turns out I forgot to add `Host`, `X-Forwarded-For` header in my nginx config.

Code from https://verdaccio.org/docs/en/reverse-proxy#sub-directory
```
location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host            $host:$server_port;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
```

After that I removed `url_prefix` from my verdaccio config and the ui worked fine

**Comment by ktemelkov** [comment]
> > See also [verdaccio.org/docs/en/reverse-proxy#sub-directory](https://verdaccio.org/docs/en/reverse-proxy#sub-directory)
> 
> I was facing a similar issue, turns out I forgot to add `Host`, `X-Forwarded-For` header in my nginx config.
> 
> Code from https://verdaccio.org/docs/en/reverse-proxy#sub-directory
> 
> ```
> location / {
>         proxy_pass http://127.0.0.1:8080;
>         proxy_set_header Host            $host:$server_port;
>         proxy_set_header X-Forwarded-For $remote_addr;
>         proxy_set_header X-Forwarded-Proto $scheme;
>     }
> ```
> 
> After that I removed `url_prefix` from my verdaccio config and the ui worked fine

Because your are not using url_prefix in your nginx configuration. The issue here is when you have something like 'location ~ ^/verdaccio/(.*)$ {'.

**Comment by ktemelkov** [comment]
As a temporary workaround I have added another location section in my nginx configuration to forward the paths starting with /-/static/ to the Verdaccio ip:port, which fortunately works for me as the website forwarded at / does not use such paths.

```
    location ~ ^/verdaccio/(.*)$ {
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header Host $host:$server_port;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_pass http://127.0.0.1:4873/$1;
    }

    location ~ ^/-/static/(.*)$ {
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header Host $host:$server_port;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_pass http://127.0.0.1:4873/-/static/$1;
    }

```
Of course with this configuration I have to set url_prefix to /verdaccio/

**Comment by juanpicado** [comment]
Closed, check https://verdaccio.org/blog/2021/04/14/verdaccio-5-migration-guide#url_prefix-improved-behavior
