### ISSUE TITLE
[Feature]: Color themes using emotion-theme

### ISSUE THREAD

**Issue by anikethsaha** [verdaccio/ui#269]
**Is your feature request related to a problem? Please describe.**
It's good to have a different color theme for the UI. Like dark mode, light mode, etc.
Theming can be done with as minimal as possible as what I saw there isn't many points where it needs to be changed.
I thought of having a separate UI theme plugin for this. But as this is not so big and huge, having a separate package to achieve different colors theme on the website won't be an efficient solution. Just a select button and its good to do.

**Describe the solution you'd like**
We can get this going using emotion's official [theme package](https://emotion.sh/docs/theming)

**Describe alternatives you've considered**
A separate package.

**Additional context**
I have done the PoC and also made support for this in my fork. https://github.com/anikethsaha/ui/tree/dark-mode

Demo from the fork (with _dark_ and _default_ theme)
![Imgur](https://imgur.com/VHlOOcL.gif)

_Just a PR behind to get this thing going_

## Snapshots

> NOTE: The default theme is the current one. Made no changes with the colors of it

- theme changing button in the header
  ![image](https://user-images.githubusercontent.com/26347874/68698926-fcf7d880-05a7-11ea-941c-d97852e91735.png)

* Navbar

default
![image](https://user-images.githubusercontent.com/26347874/68698854-d6d23880-05a7-11ea-835e-4288f07ad9f4.png)

dark

![image](https://user-images.githubusercontent.com/26347874/68698946-084b0400-05a8-11ea-8b3d-3b28b54ea028.png)

- front page

default
![image](https://user-images.githubusercontent.com/26347874/68699024-34668500-05a8-11ea-8c4b-47da50e428ca.png)

dark
![image](https://user-images.githubusercontent.com/26347874/68699007-27499600-05a8-11ea-856d-0f8d9ecccc31.png)

- detail page

default
![image](https://user-images.githubusercontent.com/26347874/68699104-60820600-05a8-11ea-93f1-bb2d43b889a2.png)

dark

![image](https://user-images.githubusercontent.com/26347874/68699076-4f38f980-05a8-11ea-9068-201f15016971.png)

**Comment by anikethsaha** [comment]
cc @juanpicado @priscilawebdev

**Comment by priscilawebdev** [comment]
Hi @anikethsaha !

Wow, I love the idea of having a dark mode in the Verdaccio UI 😀👏 

I created a separate folder called muiComponents, first because of the forwardRef problem, but my biggest motivation behind this is to create theme. For a long time, I want to use ThemeProvider from the Material UI, but I haven't really had enough time to do this so far. I think it will be easier because we are already using their components and they have such good documentation + a very active community + always improving. I would say I'm a big fan 🙃

What do you think we implemented together, also adding the dark mode?

**Comment by juanpicado** [comment]
hi @anikethsaha great, one suggestion, rather to use the green logo, why don't use the black one https://verdaccio.org/docs/en/logo ? ;-) then you would get a better combination.

@priscilawebdev I like the idea of https://material-ui.com/customization/theming/ and I know that's what we are pursuing, but I'm not sure how far are we from that, could you create a detailed ticket explaining it? eg: steps already done, what's missing, some docs so people can help each step, etc etc. 

I see both approaches are similar but the PoC requires changes in several components and I'm afraid https://github.com/verdaccio/ui/issues/221 would be a problem, why? because we need to decide which styling library use, **we cannot use both**.

So, let's expose first how far are we for theming with Material-UI and then we can decide which `ThemeProvider` we should use in short-term.

**Comment by juanpicado** [comment]
@anikethsaha @priscilawebdev furthermore, would be great to have a new package `@verdaccio/logo` in monorepo with all svg on it? ... just an idea.

**Comment by anikethsaha** [comment]
I am + 1for either of theme provider.
What I saw by implementing using `emotion` is that it was quite easy to integrate and with 0 rewrite of any component core. 
But i can see that `material-ui` is pretty advance and has some good api to support it. 
I guess we can have one PoC with material. 

Also here is not just dark mode, we can have more theme as well https://github.com/anikethsaha/ui/blob/dark-mode/src/App/theme.ts

@juanpicado yeah that's good one, we can have dark logo 🤩

Instead of `@verdaccio/logo` , what as about `@verdaccio/components/logo`.
We can have some re usable components that can work with different verdaccio theme. Not just with this theme. Like others creating custom theme for verdaccio, they can use some official verdaccio components that can be plug with any styling, and components library. 

What do you think?

**Comment by juanpicado** [comment]
> Instead of @verdaccio/logo , what as about @verdaccio/components/logo.

My point is create a distribution of logo, so can be used also in the website as dependency, not only in UI.

**Comment by anikethsaha** [comment]
Yeah It would be good to have it.

**Comment by priscilawebdev** [comment]
@juanpicado @anikethsaha I have done some tests and my final conclusion is: We really need to update emotion in order to use it's theme.

I will open a PR still in progress adding the theme :-)

**Comment by anikethsaha** [comment]
> We really need to update emotion in order to use it's theme

Updating emotion is again a pain point of itself. Even I tried that before this PoC and had quite a good number of type errors.
I guess using material-ui theme provider can work here.

_But again we need to migrate to emotion@10_

**Comment by anikethsaha** [comment]
also, @priscilawebdev would appreciate if you can create a tracking issue :octocat:  for the theme.

**Comment by priscilawebdev** [comment]
@anikethsaha I have just done the emotion migration + added the theme (a part of it). Please see https://github.com/verdaccio/ui/pull/286

**Comment by anikethsaha** [comment]
@priscilawebdev can we do the custom component styling using material itself. https://material-ui.com/customization/components/
Having both emotion and material may increase the load and those snapshots might not be consistent.

Material does use a styling library (https://github.com/mui-org/material-ui/blob/master/packages/material-ui-styles/package.json#L52-L59) so we can use that too if required

**Comment by juanpicado** [comment]
@priscilawebdev your RP https://github.com/verdaccio/ui/pull/286 means we are betting for emotion rather any other library?

@anikethsaha I think @priscilawebdev mentioned few months ago the performance issues that Material-ui styles has, I think se can elaborate a bit more.

@anikethsaha would you like yo review https://github.com/verdaccio/ui/pull/286 ?

**Comment by anikethsaha** [comment]
> @anikethsaha I think @priscilawebdev mentioned few months ago the performance issues that Material-ui styles has, I think she can elaborate a bit more.

Yea, i guess we can discuss this a bit 
Can you mention the issue or PR where you had the discussion. 

What I can right now is that this ui has currently 2 css in js library. _material is using jss_

Although the material's stlyling is opt-in-out integration so in the final bundle I dont think those will be included if material-styled is not being used. 

But still I can say that having one styling library throughout the project would be better. 

In #286, the emotion v10 is done and that is a major relief. We can now decide the styling thing. 

I will try to compare bundlsize of each PoCs.

**Comment by priscilawebdev** [comment]
Hi @anikethsaha yes I agree with you. If I haven't had some problems with Material UI, I would love to use only this library, but as you can see in this issue: https://github.com/mui-org/material-ui/issues/17196 I had some performance issues, because of the jss. I am also aware that MUI will migrate again to styled-components.. 

![image](https://user-images.githubusercontent.com/29228205/69223502-c576c680-0b7b-11ea-9aec-98d7bcc046e1.png)

I find it a pity, because I love the makeStyles API...it's really handy...but not performance friendly...

This week I am a bit busy, but next week on Tuesday I will check the bundle size and compare everything, then we can discuss more about it 😉

**Comment by anikethsaha** [comment]
https://github.com/mui-org/material-ui/issues/16756#issuecomment-527848720

Yeah....bad idea to use material/styled right now. maybe later when they migrate to styled-component

let's keep emotion then 👍 . 

> This week I am a bit busy, but next week on Tuesday I will check the bundle size and compare everything, then we can discuss more about it 😉

Yea sure! anyway, I don't think we need other option right now!, I am +1 for this one 😃

**Comment by juanpicado** [comment]
Ok guys @anikethsaha @priscilawebdev has added theme support, I think we can move this ahead. @anikethsaha would you like to PoC again on top of the new theme provider?

**Comment by anikethsaha** [comment]
> @anikethsaha would you like to PoC again on top of the new theme provider?

I guess the current looks good 💯 . Excited to add some themes in the future 😃.

I guess this issue is good to close 👍
