### ISSUE TITLE
Verify wether identity-obj-proxy in Jest works

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/ui#93]
We should not mock this due to we uses `identity-obj-proxy` to do it out of the box, but If I remove the mock the test fails, thus, the configuration seems does not work fine. I'll address this in a new ticket.
https://github.com/keyz/identity-obj-proxy
See example here.
https://github.com/verdaccio/ui/blob/4.x-master/jest.config.js#L16

_Originally posted by @juanpicado in https://github.com/verdaccio/ui/pull/92/review_comment/create_

**Comment by sergiohgz** [comment]
In the example referenced at https://github.com/keyz/identity-obj-proxy, the images are mocked with a stub file config. I don't see any site where they use identity-obj-proxy for this purpose, so we would make the workaround. What do you think? @juanpicado @ayusharma

**Comment by juanpicado** [comment]
Yeah, I'm confused about the current usage. https://jestjs.io/docs/en/webpack#mocking-css-modules Even they only reference webpack or CSS modules and that's is what @griffithtp is removing here https://github.com/verdaccio/ui/pull/85 , so perhaps we do not need that anymore and @ayusharma is right with this approach.

**Comment by sergiohgz** [comment]
We can use it to mock svg files.
Currently, the svg transformer in https://github.com/verdaccio/ui/blob/4.x-master/jest.config.js#L17 is not working because it doesn't exist. But if we use `identity-obj-proxy` (we can join s?css and svg definition in line 14) we don't need to mock svg files anymore like we did in https://github.com/verdaccio/ui/blob/4.x-master/src/components/Engines/Engines.test.tsx#L5

**Comment by priscilawebdev** [comment]
closing this for now
